---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u5786596/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp single-project-web-cendekia.html $DEPLOYPATH
    - /bin/cp work-listing.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R document $DEPLOYPATH
    - /bin/cp -R favicon $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH